# Generated by Django 6.0.6 on 2026-07-15 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_status',
            field=models.CharField(choices=[('unverified', 'Не подтвержден'), ('verified', 'Подтвержден'), ('bounced', 'Ошибка доставки (Bounced)')], default='unverified', max_length=15, verbose_name='Статус Email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=True, verbose_name='Согласен на получение маркетинговых рассылок'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения подписки'),
        ),
    ]
