# Generated by Django 6.0.5 on 2026-06-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название статьи",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите текст статьи", verbose_name="Содержимое"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью товара",
                        null=True,
                        upload_to="blog_previews/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть статью",
                        verbose_name="Признак публикации",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
                "ordering": ["-created_at"],
            },
        ),
    ]
