# Generated by Django 6.0.6 on 2026-07-09 07:40

from django.apps import apps as global_apps
from django.db import migrations


def create_content_managers_group(apps, schema_editor):
    """Автоматически создает группу 'Контент менеджеры' и наделяет её правами управления постами.

    Эта функция предназначена для запуска внутри механизма Data-миграций Django
    (`migrations.RunPython`). Она гарантирует, что при развертывании проекта на новой
    базе данных (включая локальную разработку, тесты и production-сервер) группа
    пользователей с необходимым набором системных и кастомных разрешений
    будет инициализирована автоматически.

    Логика работы:
        1. Безопасно находит или создает в таблице `auth_group` запись с именем 'Контент менеджеры'.
        3. Извлекает стандартные CRUD-права Django, сгенерированные автоматически для модели Post.
        4. Связывает все полученные права с группой через промежуточную таблицу (Many-to-Many).

    Args:
        apps (django.apps.registry.Apps): Реестр приложений Django, предоставляющий
            доступ к историческим состояниям моделей в контексте текущей миграции.
            Используется вместо прямого импорта моделей для предотвращения конфликтов.
        schema_editor (django.db.backends.base.schema.BaseDatabaseSchemaEditor):
            Редактор схемы базы данных, предоставляемый Django для выполнения низкоуровневых
            изменений структуры БД (в данной функции напрямую не используется, но обязателен
            для сигнатуры `RunPython`).

    Raises:
        django.core.exceptions.ObjectDoesNotExist: Если одно из запрашиваемых разрешений
            не найдено в базе данных. Это может произойти, если база данных еще не знает
            о модели `Blog` или если её миграции не были применены ранее.

    Examples:
        Внутри файла миграции функция регистрируется в блоке операций:
        >>> operations = [
        ...     migrations.RunPython(create_content_managers_group),
        ... ]
    """

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # Получаем группу
    group, created = Group.objects.get_or_create(name="Контент менеджеры")

    # Гарантируем, что Django создаст системные права до выполнения нашего фильтра
    # Используем глобальный config (global_apps), чтобы избежать ошибки AppConfigStub
    from django.contrib.auth.management import create_permissions

    for app_config in global_apps.get_app_configs():
        app_config.models_module = True  # Защита от AttributeError: 'AppConfigStub' object has no attribute 'models_module'
        create_permissions(app_config, apps=apps, verbosity=0)

    # Находим системные права Django для модели Post
    # (Они создаются автоматически, codename у них всегда add_ИМЯМОДЕЛИ, change_ИМЯМОДЕЛИ и т.д.)
    # Кроме delete_blog из соображений безопасности
    # Находим права через filter (это безопаснее, так как код не упадет, если какого-то права вдруг нет)
    required_permissions = Permission.objects.filter(
        codename__in=["add_post", "change_post", "view_post"]
    )

    # Добавляем весь найденный набор прав группе
    group.permissions.add(*required_permissions)


def remove_content_managers_group(apps, schema_editor):
    """Удаляет группу при откате миграции."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Контент менеджеры").delete()


class Migration(migrations.Migration):
    dependencies = [
        # Первая миграция от станрдартного приложение auth, чтобы не возникало ошибок
        ("auth", "__first__"),
        # '0001_initial' имя ПРЕДЫДУЩЕЙ миграции в приложении blog,
        # чтобы модели этого приложения уже гарантированно существовали в базе данных.
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_content_managers_group, reverse_code=remove_content_managers_group
        ),
    ]
