# Generated by Django 6.0.5 on 2026-05-26 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="cost",
            new_name="price",
        ),
    ]
