# Generated by Django 6.0.6 on 2026-07-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                max_length=170,
                unique=True,
                verbose_name="URL-слаг",
            ),
            preserve_default=False,
        ),
    ]
