# Generated by Django 6.0.6 on 2026-07-08 16:41

from django.apps import apps as global_apps
from django.db import migrations


def fill_moderator_permissions(apps, schema_editor):
    """Автоматически создает группу 'Модераторы' и наделяет её правами управления товарами.

    Эта функция предназначена для запуска внутри механизма Data-миграций Django
    (`migrations.RunPython`). Она гарантирует, что при развертывании проекта на новой
    базе данных (включая локальную разработку, тесты и production-сервер) группа
    пользователей с необходимым набором системных и кастомных разрешений
    будет инициализирована автоматически.

    Логика работы:
        1. Безопасно находит или создает в таблице `auth_group` запись с именем 'Модераторы'.
        2. Извлекает из таблицы `auth_permission` кастомное право на снятие товаров с публикации.
        3. Извлекает стандартные CRUD-права Django, сгенерированные автоматически для модели Product.
        4. Связывает все полученные права с группой через промежуточную таблицу (Many-to-Many).

    Args:
        apps (django.apps.registry.Apps): Реестр приложений Django, предоставляющий
            доступ к историческим состояниям моделей в контексте текущей миграции.
            Используется вместо прямого импорта моделей для предотвращения конфликтов.
        schema_editor (django.db.backends.base.schema.BaseDatabaseSchemaEditor):
            Редактор схемы базы данных, предоставляемый Django для выполнения низкоуровневых
            изменений структуры БД (в данной функции напрямую не используется, но обязателен
            для сигнатуры `RunPython`).

    Raises:
        django.core.exceptions.ObjectDoesNotExist: Если одно из запрашиваемых разрешений
            не найдено в базе данных. Это может произойти, если база данных еще не знает
            о модели `Product` или если её миграции не были применены ранее.

    Examples:
        Внутри файла миграции функция регистрируется в блоке операций:
        >>> operations = [
        ...     migrations.RunPython(fill_moderator_permissions),
        ... ]
    """

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # Получаем группу
    moderators, created = Group.objects.get_or_create(name="Модераторы")

    # Гарантируем, что Django создаст системные права до выполнения нашего фильтра
    # Используем глобальный config (global_apps), чтобы избежать ошибки AppConfigStub
    from django.contrib.auth.management import create_permissions

    for app_config in global_apps.get_app_configs():
        app_config.models_module = True  # Защита от AttributeError: 'AppConfigStub' object has no attribute 'models_module'
        create_permissions(app_config, apps=apps, verbosity=0)

    # Находим права через фильтр, так безопаснее
    required_permissions = Permission.objects.filter(
        codename__in=[
            "can_unpublish_product",  # Кастомное право
            "add_product",
            "change_product",
            "view_product",
            "delete_product",
        ]
    )

    # Добавляем весь этот набор прав группе модераторов
    moderators.permissions.add(*required_permissions)


def remove_content_managers_group(apps, schema_editor):
    """Удаляет группу при откате миграции."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Модераторы").delete()


class Migration(migrations.Migration):
    dependencies = [
        # 1. Первая миграция от стандартного приложения auth (оставляем без изменений)
        ("auth", "__first__"),

        # 2. ИСПРАВЛЕНИЕ: Связываем цепочку с файлом 0002 из вашей папкиmigrations
        ("catalog", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.RunPython(
            fill_moderator_permissions, reverse_code=remove_content_managers_group
        ),
    ]
