# Generated by Django 6.0.5 on 2026-06-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_cost_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото товара",
                null=True,
                upload_to="photo/",
                verbose_name="Фото",
            ),
        ),
    ]
