# Generated by Django 6.0.6 on 2026-07-19
from django.db import migrations


def create_system_groups(apps, schema_editor):
    """Автоматически создает системные группы 'Модераторы' и 'Контент-менеджеры'

    с жестким разграничением прав согласно ТЗ безопасности интернет-магазина.
    """
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # =========================================================================
    # --- 1. ГРУППА: МОДЕРАТОРЫ ---
    # =========================================================================
    moderators_group, created = Group.objects.get_or_create(name='Модераторы')

    # А. Права для работы с Блогом и Каталогом (Только просмотр и изменение)
    mod_content_perms = Permission.objects.filter(
        content_type__app_label__in=['blog', 'catalog'],
        codename__in=[
            'view_product', 'change_product',
            'view_category', 'change_category',
            'view_article', 'change_article'
        ]
    )

    # Б. Права для Пользователей (Только изменение, чтобы делать неактивными)
    mod_user_perms = Permission.objects.filter(
        content_type__app_label='users',
        codename__in=['change_customuser']
    )

    # Объединяем и привязываем права к Модераторам (Доступа к 'mailings' у них НЕТ)
    moderators_group.permissions.set(list(mod_content_perms) + list(mod_user_perms))

    # =========================================================================
    # --- 2. ГРУППА: КОНТЕНТ-МЕНЕДЖЕРЫ ---
    # =========================================================================
    content_group, created = Group.objects.get_or_create(name='Контент-менеджеры')

    # Автоматически собираем ВСЕ права для Блога, Каталога и Рассылок.
    # Приложение 'users' сюда НЕ ВКЛЮЧАЕМ для безопасности профилей клиентов.
    content_permissions = Permission.objects.filter(
        content_type__app_label__in=['blog', 'catalog', 'mailings']
    ).exclude(
        # Защита витрины: забираем у менеджера права на полное УДАЛЕНИЕ категорий и товаров
        codename__in=['delete_product', 'delete_category']
    )

    # Железобетонно привязываем собранный пакет прав к Контент-менеджерам
    content_group.permissions.set(content_permissions)


def remove_system_groups(apps, schema_editor):
    """Откат миграции: безопасно удаляет группы при отзыве миграции назад."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Модераторы', 'Контент-менеджеры']).delete()


class Migration(migrations.Migration):
    dependencies = [
        # Зависимость от предыдущей миграции каталога
        ('catalog', '0002_alter_category_slug'),

        # Зависимости от начальных миграций всех рабочих приложений проекта.
        # Это гарантирует, что Django сначала поднимет все таблицы и сгенерирует права,
        # и только потом наш скрипт свяжет их с группами на чистой базе наставника!
        ('mailings', '0001_initial'),
        ('blog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_system_groups, reverse_code=remove_system_groups),
    ]
