# Generated by Django 6.0.5 on 2026-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Введите уникальный артикул товара",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Артикул",
            ),
        ),
    ]
