# Generated by Django 6.0.6 on 2026-07-08 16:41

from django.db import migrations


def fill_moderator_permissions(apps, schema_editor):
    """Автоматически создает группу 'Модераторы' и наделяет её правами управления товарами.

        Эта функция предназначена для запуска внутри механизма Data-миграций Django
        (`migrations.RunPython`). Она гарантирует, что при развертывании проекта на новой
        базе данных (включая локальную разработку, тесты и production-сервер) группа
        пользователей с необходимым набором системных и кастомных разрешений
        будет инициализирована автоматически.

        Логика работы:
            1. Безопасно находит или создает в таблице `auth_group` запись с именем 'Модераторы'.
            2. Извлекает из таблицы `auth_permission` кастомное право на снятие товаров с публикации.
            3. Извлекает стандартные CRUD-права Django, сгенерированные автоматически для модели Product.
            4. Связывает все полученные права с группой через промежуточную таблицу (Many-to-Many).

        Args:
            apps (django.apps.registry.Apps): Реестр приложений Django, предоставляющий
                доступ к историческим состояниям моделей в контексте текущей миграции.
                Используется вместо прямого импорта моделей для предотвращения конфликтов.
            schema_editor (django.db.backends.base.schema.BaseDatabaseSchemaEditor):
                Редактор схемы базы данных, предоставляемый Django для выполнения низкоуровневых
                изменений структуры БД (в данной функции напрямую не используется, но обязателен
                для сигнатуры `RunPython`).

        Raises:
            django.core.exceptions.ObjectDoesNotExist: Если одно из запрашиваемых разрешений
                не найдено в базе данных. Это может произойти, если база данных еще не знает
                о модели `Product` или если её миграции не были применены ранее.

        Examples:
            Внутри файла миграции функция регистрируется в блоке операций:
            >>> operations = [
            ...     migrations.RunPython(fill_moderator_permissions),
            ... ]
    """

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Получаем группу
    moderators, created = Group.objects.get_or_create(name='Модераторы')

    # Находим наше кастомное право
    can_unpublish = Permission.objects.get(codename='can_unpublish_product')

    # Находим системные права Django для модели Product
    # (Они создаются автоматически, codename у них всегда add_ИМЯМОДЕЛИ, change_ИМЯМОДЕЛИ и т.д.)
    can_create = Permission.objects.get(codename='add_product')
    can_edit = Permission.objects.get(codename='change_product')
    can_delete = Permission.objects.get(codename='delete_product')
    can_view = Permission.objects.get(codename='view_product')

    # Добавляем весь этот набор прав группе модераторов
    moderators.permissions.add(
        can_unpublish,
        can_create,
        can_edit,
        can_delete,
        can_view
    )

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options'),
    ]

    operations = [
        migrations.RunPython(fill_moderator_permissions),
    ]
