# Generated by Django 6.0.5 on 2026-06-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                default="TEMP-SKU",
                help_text="Введите уникальный артикул товара (обязательно)",
                max_length=50,
                unique=True,
                verbose_name="Артикул",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photo/", verbose_name="Фото")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        to_field="sku",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография товара",
                "verbose_name_plural": "Галерея товара",
            },
        ),
    ]
