# Generated by Django 6.0.6 on 2026-07-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Опубликован'),
        ),
    ]
